apiVersion: v1
kind: Service
metadata:
  name: hance-frontend
spec:
  type: NodePort # 我們回到 NodePort 模式，以進行更底層的除錯
  selector:
    app: hance-frontend
  ports:
    - protocol: TCP
      port: 9301
      targetPort: 80
