name: Deploy to VM

on:
  push:
    branches:
      - main # 當推送到 main 分支時觸發

jobs:
  build-and-deploy:
    # 這是關鍵：指定此任務要在自託管的執行器上執行
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore backend secret from GitHub Secrets
        run: echo "${{ secrets.K8S_BACKEND_SECRET_B64 }}" | base64 --decode > k8s/backend-secret.yaml

      - name: Run Skaffold
        # 執行此指令，將後續的 docker 指令都指向 Minikube 內部的 Docker daemon
        run: |
          eval $(minikube -p minikube docker-env)
          skaffold run --filename skaffold.yaml
